### ISSUE TITLE
Wrong y-axis on 'Variants by Position' chart

### ISSUE THREAD

**Issue by mattsoup** [bwlang/primer_monitor#33] opened 2021-08-20 14:38 UTC
On my screen at least, the y-axis goes 0->1->1, when (I assume) it should go 0->0.5->1

![Screen Shot 2021-08-20 at 10 38 12 AM](https://user-images.githubusercontent.com/28735187/130250204-011fb28c-aae1-4120-a44a-a90c31472213.png)

**Comment by Valiec** [comment] 2023-07-25 18:53
I can't reproduce this issue, it says 0 -> 0.5 -> 1 for me.

Given it's from 2021, I'm assuming it's been fixed, so I'm closing it to clean up the issues list.

If it's still happening, just reopen this.

**Closed by Valiec** 2023-07-25 18:53 UTC
